# -------------------------- #
#   SOURCES ENDPOINT ERRORS  #
# -------------------------- #

all:
  - code: "400"
    responses:
      - method: "post"
        condition: "Source's `display_name` is already in use"
        version: "all"
        response-body: |
          `"a source of name <NAME> already exists"`

      - method: "post"
        condition: "Prohibited arguments"
        version: "all"
        response-body: |
          `"POST body may only include a type, a display_name and map of string properties"`

      - method: "put"
        condition: "Invalid source ID"
        version: "all"
        response-body: |
          `"unable to locate source(<SOURCE_ID>) for client (<ACCOUNT_ID>) to update"`

      - method: "put"
        condition: "Prohibited arguments"
        version: "all"
        response-body: |
          `"PUT body many only include the keys: display_name and properties"`

      - method: "post, put"
        condition: "Invalid `properties` data"
        version: "all"
        response-body: |
          An array of the `property` names containing invalid data:

          ```json
          {
             "bad_properties":[
                "start_date",
                "frequency_in_minutes"
             ],
             ...
          }
          ```

          May result from incorrect formatting, incorrect typing (all property values must be strings), or a property has a value that is an empty string.

      - method: "delete"
        condition: "Prohibited arguments"
        version: "all"
        response-body: |
          `"DELETE body must be empty"`

      - method: "delete"
        condition: "Invalid source ID"
        version: "all"
        response-body: |
          `"Unable to locate source(<SOURCE_ID>) for client (<ACCOUNT_ID>) to delete"`