## NEED HELP USING THIS TEMPLATE? SEE:
## https://docs-about-stitch-docs.netlify.com/reference/common-templates/database-connection-settings/


# -------------------------- #
#    [NAME] CONNECTION UI    #
# -------------------------- #

## This file contains the properties required to successfully set up
## a [NAME] connection in Stitch.


# -------------------------- #
#            [NAME]           #
# -------------------------- #

[database-name]:
## HOST/ENDPOINT
  - name: "{{ site.data.ui.common.database-connections.field-names.host }}"
    copy: "{{ site.data.ui.common.database-connections.field-copy.host | flatify }}"

## PORT
  - name: "{{ site.data.ui.common.database-connections.field-names.port }}"
    copy: "{{ site.data.ui.common.database-connections.field-copy.port | flatify }}"

## USERNAME
  - name: "{{ site.data.ui.common.database-connections.field-names.username }}"
    copy: "{{ site.data.ui.common.database-connections.field-copy.username | flatify }}"

## PASSWORD
  - name: "{{ site.data.ui.common.database-connections.field-names.password }}"
    copy: "{{ site.data.ui.common.database-connections.field-copy.password | flatify }}"

## DATABASE
  - name: "{{ site.data.ui.common.database-connections.field-names.database }}"
    copy: "{{ site.data.ui.destination-settings.common.field-copy.destination-database | flatify }}"