# -------------------------- #
#        SCHEMA OBJECT       #
# -------------------------- #

title: "Schema"

section: "#schema-object"

description: |
  A Schema object contains a valid JSON schema describing the record(s) in a [Message object's]({{ site.data.import-api.data-structures.message.section }}) `data` property.

  Refer to the [JSON schema](https://json-schema.org){:target="new"} docs for more info about JSON schemas.