name: Build
permissions:
  id-token: write
  contents: write
on:
#  push:
#    branches:
#      - master
  workflow_dispatch:

env:
  AWS_REGION: "us-east-1"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Build Jekyll site
        run: bundle exec jekyll build
        env:
          JEKYLL_ENV: production

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: _site/


