name: Build
permissions:
  id-token: write
  contents: write
on:
#  push:
#    branches:
#      - master
  workflow_dispatch:

env:
  AWS_REGION: "us-east-1"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Git clone the repository
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v7.0.1
#    - name: Build with Hugo
#      uses: jakejarvis/hugo-build-action@eba25f02a13bdbcd8e637e0daac2487456c74d9d # v0.85.0
#      with:
#        args: --minify --buildDrafts



