name: Generate foreign keys
on:
  push:
    paths:
      - '**-foreign-keys.yml'
    branches:
      - '!master'

jobs:
  generate-foreign-keys:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Python modules
        uses: BSFishy/pip-action@v1
        with:
          packages: |
            pyyaml

      - name: Generate foreign keys
        run: python generate_foreign_keys.py
        working-directory: ./scripts/json

      - name: Check for changes
        id: get_changes
        run: echo "::set-output name=changed::$(git status --porcelain | wc -l)"
      
      - name: Commit changes
        if: steps.get_changes.outputs.changed != 0
        run: |
          git add -A
          git config --global user.email "github-actions@github.com"
          git config --global user.name 'github-actions'
          git commit -am "Automated commit: Generate JSON schemas"
          git push
